### ISSUE TITLE
"TypeError: Cannot read property 'startActivity' of undefined"

### ISSUE THREAD

**Issue by dgmltn** [Aietes/node-red-contrib-harmony#2] opened 2017-02-18 06:59 UTC
After a while (?) my H activity node stops working properly. The hub will search for and find the hub right away, but the activity starts displaying a number instead of the the activity name. The activity search button says "loading activities..." forever, and then when the start activity is triggered, I get this error:

msg : error
"TypeError: Cannot read property 'startActivity' of undefined"

**Comment by Aietes** [comment] 2017-02-19 19:33
It sounds like this happens because your Harmony Hub changed its IP. Can you post the more detailed error message with the line number here?

**Comment by dgmltn** [comment] 2017-02-20 00:20
Ok, I'll pay more attention to the IP Address. I'll also try setting a static IP address in my router. Could this happen if the IP address lease expires, even if the address does not change?

How would I find the more detailed error message in the context of Node-RED?

**Comment by dgmltn** [comment] 2017-02-24 05:33
Well, it happened again, and the IP address is still the same. I haven't been able to find any logs or detailed stack trace about the error.

**Comment by strelniece** [comment] 2017-03-02 13:40
Sounds like sort of the same problem as I have.

Sometimes it works, and sometimes not... :) 

node-red-log gives 

errorhub { Error: MAX_CLIENTS=6
at Connection.onStanza (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:355:17)
at StreamParser.<anonymous> (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:226:10)
at emitOne (events.js:96:13)
at StreamParser.emit (events.js:188:7)
at SaxLtx.<anonymous> (/home/pi/.node-red/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
at emitOne (events.js:96:13)
at SaxLtx.emit (events.js:188:7)
at SaxLtx._handleTagOpening (/home/pi/.node-red/node_modules/ltx/lib/parsers/ltx.js:31:18)
at SaxLtx.write (/home/pi/.node-red/node_modules/ltx/lib/parsers/ltx.js:105:26)
at StreamParser.write (/home/pi/.node-red/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
at Connection.onData (/home/pi/.node-red/node_modules/node-xmpp-core/lib/Connection.js:305:17)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:548:20)
stanza:
Stanza {
name: 'stream:error',
parent: null,
children: [ [Object], [Object] ],
attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' } } }

**Comment by dgmltn** [comment] 2017-03-02 16:30
I think it is a reconnect issue, it becomes disconnected after a while and then does not properly reconnect.

@strelniece your bug is mentioned in the underlying harmony library: https://github.com/swissmanu/harmonyhubjs-client/issues/34

And my issue is mentioned too: https://github.com/swissmanu/harmonyhubjs-client/issues/31

**Comment by strelniece** [comment] 2017-03-03 18:25
Let's hope it will be a fix soooooon

**Comment by dgmltn** [comment] 2017-03-03 18:48
I think some sort of reconnection strategy is in order... Whether that's done in node-red-contrib-harmony or harmonyhubjs-client though is up for debate ... @aietes do you have any thoughts?

**Comment by Aietes** [comment] 2017-03-07 11:42
I'm just back from vacation, I'll look into it an implement an automatic reconnection soon, hopefully I can release it this week.

**Comment by Aietes** [comment] 2017-03-12 21:47
I can't really solve the issue, as it needs to be addressed in the underlying library. I pushed a new version 1.0.6 with a reconnect on timeout, can you please try if this helps mitigate the problem?

**Comment by dgmltn** [comment] 2017-03-12 23:11
Thanks a lot for the help. Just upgraded to 1.0.6, :crossed_fingers:

**Comment by Aietes** [comment] 2017-03-14 13:44
Does it work for you guys? I couldn't reproduce the error, so I have to rely on you for testing :)

**Comment by dgmltn** [comment] 2017-03-14 23:52
I installed it but didn't get the chance to test it thoroughly yet. The error occurs after a day or so, for me.

**Comment by dgmltn** [comment] 2017-03-15 04:45
No, I'm still seeing the same error message, "TypeError: Cannot read property 'startActivity' of undefined"

**Comment by dgmltn** [comment] 2017-03-15 04:46
When this happens, also I cannot look up the activity name for the integer activity anymore on the Node RED UI. I see "Loading activities..." forever after clicking the magnifying glass.

**Comment by Aietes** [comment] 2017-03-30 21:57
I just fixed another bug that appeared after deploying nodes a couple of times. Possibly your problem was related to the same bug. I would appreciate if you can give this new version 1.0.7 a try.

**Comment by dgmltn** [comment] 2017-03-31 06:43
Thanks for the update! I just npm update'd this module, so far it works great, but my problem came after a duration of time. I won't have access to this computer for a week so I will try it when I get back!

**Comment by dgmltn** [comment] 2017-03-31 07:21
I did see this in the logs just now, but the rules are still working:

Disconnected from Harmony Hub: Error: Timed out after 50000 ms

**Comment by dgmltn** [comment] 2017-03-31 08:17
Well, I waited a bit longer and now got the same error message when trying to "PowerOff". But I did catch this more detailed error message in the log:

```
31 Mar 01:14:50 - [error] [H activity:Power Off TV] TypeError: Cannot read property 'startActivity' of undefined
errorhub { Error: MAX_CLIENTS=6
at Connection.onStanza (/home/doug/.node-red/node_modules/node-xmpp-core/lib/Connection.js:355:17)
at StreamParser.<anonymous> (/home/doug/.node-red/node_modules/node-xmpp-core/lib/Connection.js:226:10)
at emitOne (events.js:96:13)
at StreamParser.emit (events.js:188:7)
at SaxLtx.<anonymous> (/home/doug/.node-red/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
at emitOne (events.js:96:13)
at SaxLtx.emit (events.js:188:7)
at SaxLtx._handleTagOpening (/home/doug/.node-red/node_modules/ltx/lib/parsers/ltx.js:31:18)
at SaxLtx.write (/home/doug/.node-red/node_modules/ltx/lib/parsers/ltx.js:105:26)
at StreamParser.write (/home/doug/.node-red/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
at Connection.onData (/home/doug/.node-red/node_modules/node-xmpp-core/lib/Connection.js:305:17)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:548:20)
stanza:
Stanza {
name: 'stream:error',
parent: null,
children: [ [Object], [Object] ],
attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' } } }
```

**Closed as completed** 2018-05-28 23:17 UTC
